services:
  fe:
    image: selectdb/doris.fe-ubuntu:2.1.8.3
    hostname: fe
    environment:
     - FE_SERVERS=fe1:192.168.194.1:9010
     - FE_ID=1
     - PRIORITY_NETWORK=192.168.194.0/24
    network_mode: host
    volumes:
      - ./doris_fe_meta:/opt/apache-doris/fe/doris-meta
      - ./doris_fe_log:/opt/apache-doris/fe/log
  be:
    image: selectdb/doris.be-ubuntu:2.1.8.3
    hostname: be
    environment:
     - FE_SERVERS=fe1:192.168.194.1:9010
     - BE_ADDR=192.168.194.1:9050
    depends_on:
      - fe
    network_mode: host
    volumes:
      - ./doris_be_storage:/opt/apache-doris/be/storage
      - ./doris_be_log:/opt/apache-doris/be/log
