networks:
  doris_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  fe:
    image: selectdb/doris.fe-ubuntu:2.1.8.3
    hostname: fe
    container_name: doris_fe
    networks:
      doris_net:
        ipv4_address: 172.18.0.10
    environment:
      - FE_SERVERS=fe1:172.18.0.10:9010
      - FE_ID=1
    ports:
      - "8030:8030"  # Web UI
      - "9020:9020"  # Edit log port
      - "9030:9030"  # Query port
      - "9010:9010"  # RPC port
    volumes:
      - ./doris_fe_meta:/opt/apache-doris/fe/doris-meta
      - ./doris_fe_log:/opt/apache-doris/fe/log
  be:
    image: selectdb/doris.be-ubuntu:2.1.8.3
    hostname: be
    container_name: doris_be
    depends_on:
      - fe
    networks:
      doris_net:
        ipv4_address: 172.18.0.11
    environment:
      - FE_SERVERS=fe1:172.18.0.10:9010
      - BE_ADDR=172.18.0.11:9050
    ports:
      - "8040:8040"  # Web UI
      - "9050:9050"  # RPC port
      - "8060:8060"  # BRPC port
    volumes:
      - ./doris_be_storage:/opt/apache-doris/be/storage
      - ./doris_be_log:/opt/apache-doris/be/log
