server:
  port: 18080

spring:
  application:
    name: otel-kafka-streams

  # Kafka Streams配置
  kafka:
    bootstrap-servers: host.orb.internal:9092
    streams:
      application-id: ${spring.application.name}
      properties:
        processing.guarantee: exactly_once_v2  # 保证exactly once语义
        commit.interval.ms: 10000              # 提交间隔，根据实际情况调整
        state.dir: ${user.home}/kafka-streams/${spring.application.name}
    consumer:
      auto-offset-reset: earliest
  # Doris数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9030/log_db
    username: root
    password: root@1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.otelkafkastreams.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 应用自定义配置
application:
  kafka:
    input-topic: otel-proto
  doris:
    table-name: otel_logs_test
    batch-size: 500         # 批处理大小
    batch-interval-ms: 1000   # 批处理时间间隔
  log-buffer:
    persistence-enabled: true # 是否启用持久化
    persistence-file: ${user.home}/log-buffer/${spring.application.name}/buffer.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 