apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace: observa-system # 可按需替换
data:
  collector-config.yaml: |-
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude: 
          - /var/log/pods/*/otel-collector/*.log  
        start_at: end
        encoding: utf-8
        include_file_name: true
        include_file_path: true
        preserve_trailing_whitespaces: true
        preserve_leading_whitespaces: false
        operators:
          - id: parser-containerd
            type: regex_parser
            regex: ^(?P<time>\S+Z)\s(?P<stream>stdout|stderr)\s(?P<logtag>[^ ]*)\s?(?P<log>.*)
            output: containerd-recombine
          - id: containerd-recombine
            type: recombine
            combine_field: attributes.log
            combine_with: ""
            source_identifier: attributes["log.file.path"]
            is_last_entry: attributes.logtag == 'F'
            max_log_size: 0
            output: extract_metadata_from_filepath
          - id: extract_metadata_from_filepath
            type: regex_parser
            parse_from: attributes["log.file.path"]
            regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
          - type: move
            from: attributes.namespace
            to: resource["k8s.namespace.name"]
          - type: move
            from: attributes.pod_name
            to: resource["k8s.pod.name"]
          - type: move
            from: attributes.uid
            to: resource["k8s.pod.uid"]
          - type: move
            from: attributes.container_name
            to: resource["k8s.container.name"]
          - type: move
            from: attributes.restart_count
            to: resource["k8s.container.restartCount"]
          - type: recombine
            combine_field: body
            is_first_entry: body matches "^[^\\s]"
            source_identifier: attributes["log.file.path"]
    processors:
      batch:
        timeout: 10s
      k8sattributes:
        auth_type: serviceAccount   # 使用k8s内部ServiceAccount权限（一般是DaemonSet自动注入）
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.container.name
            - k8s.pod.uid
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
    exporters:
      kafka:
        brokers: ["kafka.kafka.orb.local:9092"]
        topic: "otel-proto"
        encoding: "otlp_proto"

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch, k8sattributes]
          exporters: [kafka]